### ISSUE TITLE
Call to undefined method Seshac\Shiprocket\ShiprocketApi::token()

### ISSUE THREAD

**Issue by vinchamp** [seshac/laravel-shiprocket-api#1]
Hi sir,
I am use this [ ShiprocketApi::token() ]code but show error plz help

Call to undefined method Seshac\Shiprocket\ShiprocketApi::token()
Thanks

**Comment by seshac** [comment]
Hey @vinchamp, Thank you for letting me, I updated the docs.

You can use like this to get token
```php
  
use Seshac\Shiprocket\Shiprocket;
.
.
.
Shiprocket::getToken()
```

**Comment by vinchamp** [comment]
Thank You, Sir
it is work now.
