### ISSUE TITLE
InvalidArgumentException

### ISSUE THREAD

**Issue by AshishGarg1988** [seshac/laravel-shiprocket-api#2]
[InvalidArgumentException] when i run following command composer require seshac/laravel-shiprocket-api 

  Package seshac/laravel-shiprocket-api at version  has a PHP requirement incompatible with your PHP version (7.2.31)

**Comment by seshac** [comment]
@AshishGarg1988 , I just added support to php 7.2.5. Please you can upgrade to 7.2.5 and use it.
Thank you!.
