### ISSUE TITLE
Not getting the token, Please help me

### ISSUE THREAD

**Issue by davidpatra20** [seshac/laravel-shiprocket-api#4]
When I am going to return token like- return  $token =  Shiprocket::token();
Getting the below error message-
Class 'App\Http\Controllers\Shiprocket' not found

 should i create a controller for Shiprocket? Please help me.
I have set the default shiprocket credentilas and it is return token in postman. Please solve the issue
![issue](https://user-images.githubusercontent.com/70462773/101917474-4b820700-3bee-11eb-99fb-fd5e411ca468.png)

**Comment by seshac** [comment]
@davidpatra20 , you need to import Shiprocker class.

```php
use Seshac\Shiprocket\Shiprocket;
```

**Comment by davidpatra20** [comment]
Thank you so much.
