### ISSUE TITLE
Call to undefined method Seshac\Shiprocket\ShiprocketApi::token()

### ISSUE THREAD

**Issue by surajitbasak109** [seshac/laravel-shiprocket-api#6]
![Screenshot from 2021-02-12 17-08-14](https://user-images.githubusercontent.com/7413104/107763835-37c16100-6d55-11eb-9004-a042a52c3c73.png)

I am using Ubuntu 20.10 OS.
PHP Version: 7.2

I published the vendor file using following command:
```bash
php artisan vendor:publish --provider="Seshac\Shiprocket\ShiprocketServiceProvider" --tag="config"
```

## Suggestion
Please add this method after the constructor in ShiprocketApi class:

```php


    /**
     * Get the login details including token (valid for 24 hours)
     *
     * @return mixed
     */

    public function token()
    {
        return $this->login([
            'email' => config('shiprocket.credentials.email'),
            'password' => config('shiprocket.credentials.password')
        ]);
    }
```

**Comment by seshac** [comment]
Please use Seshac\Shiprocket\Shiprocket::token()

**Comment by surajitbasak109** [comment]
> Please use Seshac\Shiprocket\Shiprocket::token()

I am alerady using the same namespace as you mentioned. And please check your ShiprocketApi.php class file. There is no token method in your class. I have foked your repo and used it
use Seshac\Shiprocket\Shiprocket;

**Comment by seshac** [comment]
@surajitbasak109 , 

It's uses Laravel facade, you find all methods at  ShiprocketApi.php file.

I updated the docs, to get token use Seshac\Shiprocket\Shiprocket::getToken()

Thanks.

**Comment by surajitbasak109** [comment]
@seshac 
Thank you. :)
Nice api sdk. And got token back when used token method.
