### ISSUE TITLE
Class 'Seshac\Shiprocket\Shiprocket' not found

### ISSUE THREAD

**Issue by rohit-developer-indien** [seshac/laravel-shiprocket-api#9]
use Seshac\Shiprocket\Shiprocket;

public function update(Request $request, $id){
       $orderDetails = [
            // refer above url for required parameters 
        ];
        $token =  Shiprocket::getToken();
        $response =  Shiprocket::order($token)->create($orderDetails);
}

Class 'Seshac\Shiprocket\Shiprocket' not found

**Comment by seshac** [comment]
@rohit-developer-indien, did you install the package correctly?

**Comment by seshac** [comment]
It's working good at my end, please reach out to me if still you have any issues.
